name: Run scala 2.11 tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  SCALA_VERSION: "2.11.12"

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - name: Get submodules
      shell: bash
      run: git submodule update --init --recursive
    - run: mill __.compile
    - uses: actions/cache/save@v3
      with:
        path: |
          **/
        key: ${{ runner.os }}-compiled-${{ github.sha }}

  idslplugin-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill idslplugin[$SCALA_VERSION].test

  idslpayload-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill idslpayload[$SCALA_VERSION].test

  core-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill core[$SCALA_VERSION].test
    - run: mill tester[$SCALA_VERSION].testOnly spinal.core.* -- -l spinal.tester.formal -l spinal.tester.psl

  core-formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill tester[$SCALA_VERSION].testOnly spinal.core.* -- -n spinal.tester.formal

  core-psl:
      needs: compile
      runs-on: ubuntu-latest
      timeout-minutes: 90
      container:
        image: ghcr.io/spinalhdl/docker:latest
      steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get-compiled
      - run: mill tester[$SCALA_VERSION].testOnly spinal.core.* -- -n spinal.tester.psl

  sim-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill sim[$SCALA_VERSION].test

  tester-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill tester[$SCALA_VERSION].testOnly spinal.tester.* -- -l spinal.tester.formal -l spinal.tester.psl

  tester-formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill tester[$SCALA_VERSION].testOnly spinal.tester.* -- -n spinal.tester.formal

  tester-psl:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill tester[$SCALA_VERSION].testOnly spinal.tester.* -- -n spinal.tester.psl

  lib-test:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill lib[$SCALA_VERSION].test
    - run: mill tester[$SCALA_VERSION].testOnly spinal.lib.* -- -l spinal.tester.formal -l spinal.tester.psl

  lib-formal:
    needs: compile
    runs-on: ubuntu-latest
    timeout-minutes: 90
    container:
      image: ghcr.io/spinalhdl/docker:latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/get-compiled
    - run: mill tester[$SCALA_VERSION].testOnly spinal.lib.* -- -n spinal.tester.formal


  lib-psl:
      needs: compile
      runs-on: ubuntu-latest
      timeout-minutes: 90
      container:
        image: ghcr.io/spinalhdl/docker:latest
      steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/get-compiled
      - run: mill tester[$SCALA_VERSION].testOnly spinal.lib.* -- -n spinal.tester.psl
      
  # scaladoc:
  #   needs: compile
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   container:
  #     image: ghcr.io/spinalhdl/docker:latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ./.github/actions/get-compiled
  #   - run: sbt unidoc
